export enum EChapterActions {
  LIST_CHAPTER = 'LIST_CHAPTER',
  SET_LIST_CHAPTER = 'SET_LIST_CHAPTER',
  ADD_CHAPTER = 'ADD_CHAPTER',
  GET_CHAPTER = 'GET_CHAPTER',
  SET_CHAPTER = 'SET_CHAPTER',
  DELETE_CHAPTER = 'DELETE_CHAPTER',
  UPDATE_CHAPTER = 'UPDATE_CHAPTER',
  SET_UPDATE_CHAPTER = 'SET_UPDATE_CHAPTER'
}
